config/routes.rb
Ahotel::Application.routes.draw do
  devise_for :managers, :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "hotels/show"
  get "hotels/new"
  root 'static_pages#home'

  get 'managers/index', as: 'manager_root'
  get 'managers/show', as: 'hotels_index'

  resources :hotels do
    resources :commits
  end

  resources :users
  resources :hotels

  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'

end

app/models/manager.rb
class Manager < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,:recoverable, :rememberable,
         :trackable, :validatable
  #attr_accessible :email, :password, :password_confirmation, :god_mode, :reports_only
  #devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :authenticate_manager!
  helper_method :sort_hotel_column, :sort_user_column, :sort_direction

  def index
    if params[:search]
      @users = User.search(params[:search]).order(sort_user_column => sort_direction).paginate(:per_page => 5, :page => params[:page])
    else
      @users = User.order(sort_user_column => sort_direction).paginate(:per_page => 5, :page => params[:page])
    end
  end

  def show
    if params[:search]
      @hotels = Hotel.search(params[:search]).order(sort_hotel_column => sort_direction).paginate(:per_page => 3, :page => params[:page])
    else
      @hotels = Hotel.all.order(sort_hotel_column => sort_direction).paginate(:per_page => 3, :page => params[:page])
    end

    if params[:approved].present?
      @hotels = Hotel.where(approved: true).order(sort_hotel_column => sort_direction).paginate(:per_page => 3, :page => params[:page])
    elsif params[:pending].present?
      @hotels = Hotel.where(pending: true).order(sort_hotel_column => sort_direction).paginate(:per_page => 3, :page => params[:page])
    elsif params[:rejected].present?
      @hotels = Hotel.where(rejected: true).order(sort_hotel_column => sort_direction).paginate(:per_page => 3, :page => params[:page])
    else
      @hotels = Hotel.all.order(sort_hotel_column => sort_direction).paginate(:per_page => 3, :page => params[:page])
    end
  end

  def User.search(search)
    if search
      where('email LIKE ?', "%#{search}%")
    else
      scoped
    end
  end

  def Hotel.search(search)
    if search
      where('title LIKE ?', "%#{search}%")
    else
      scoped
    end
  end


  private

    def sort_hotel_column
      Hotel.column_names.include?(params[:sort]) ? params[:sort] : "title"
    end

    def sort_user_column
      Hotel.column_names.include?(params[:sort]) ? params[:sort] : "email"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction].to_sym : :asc
    end

end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/views/managers/_list_of_hotels.html.erb
<h2>Hotels</h2>
<%= form_tag hotels_index_path, :method => 'get' do %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
    <p>
      <%= "Pending" %> <%= check_box_tag :pending %>
      <%= "Approved" %> <%= check_box_tag :approved %>
      <%= "Rejected" %> <%= check_box_tag :rejected %>
      <%= submit_tag "Status Filter", :name => nil %>
    </p>
<% end %>

<table class="pretty">
  <thead>
    <tr>
      <th>№</th>
      <th><%= sortable_hotel "title"%></th>
      <th>User ID</th>
      <th>Statuses</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>




<% @hotels.each do |hotel| %>
  <tr>
    <td><%= hotel.id%></td>
    <td><%= hotel.title %></td>
    <td><%= hotel.user_id %></td>
    <td>
        <% case %>
          <% when hotel.pending===true%>
            <%= 'pending' %>
          <% when hotel.approved===true%>
            <%= 'approved' %>
          <% else %>
            <%= 'rejected' %>
        <% end %>
    </td>

    <td>
      <%if hotel.pending===true%>
      <%= link_to 'Edit', edit_hotel_path(hotel), :class => "btn btn-inverse btn-mini" %> &nbsp;
      <%end%>
    <%= link_to 'Delete', hotel_path(hotel),:class => "btn btn-inverse btn-mini", :method => 'delete', :confirm => 'Are you sure?' %></td>
  </tr>
<% end %>
  </tbody>
</table>
<%= will_paginate @hotels%>

<%= link_to 'New Hotel', new_hotel_path, :class => "btn btn-success" %>

app/views/managers/_list_of_users.html.erb
<h2>Users</h2>


<%= form_tag manager_root_path, :method => 'get' do %>
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>


<table class="pretty">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= sortable_user "email"%></th>
      <th>Hotels</th>
      <th>Commits</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>

<% @users.each do |user| %>
  <tr>
    <td><%= user.id%></td>
    <td><%= user.email %></td>

    <td><%= user.hotels.count %></td>
    <td><%= user.commits.count %></td>
    <td><%= link_to 'Edit', edit_user_path(user), :class => "btn btn-inverse btn-mini" %> &nbsp;
    <%= link_to 'Delete', user_path(user),:class => "btn btn-inverse btn-mini", :method => 'delete', :confirm => 'Are you sure?' %></td>
  </tr>
<% end %>
  </tbody>
</table>
<%= will_paginate @users%>

<%= link_to 'New User', new_user_registration_path, :class => "btn btn-success" %>

app/views/managers/index.html.erb
<h1>Administrator panel</h1>
  <%= render 'managers/list_of_users' %>
<br><br>
<%= link_to 'Users management panel', manager_root_path %> |
<%= link_to 'Hotels management panel', hotels_index_path %> 

app/views/managers/show.html.erb
<h1>Administrator panel</h1>
<%= render 'managers/list_of_hotels' %>
<br><br>
<%= link_to 'Users management panel', manager_root_path %> |
<%= link_to 'Hotels management panel', hotels_index_path %>