config/routes.rb
Ahotel::Application.routes.draw do
  devise_for :managers, :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "hotels/show"
  get "hotels/new"
  root 'static_pages#home'

  get 'managers/index', as: 'manager_root'
  get 'managers/show', as: 'hotels_index'

  resources :hotels do
    resources :commits
  end

  resources :users
  resources :hotels

  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'

end

app/views/layouts/_advertisement.html.erb
<div class="span2">
  <h3>Advertisement</h3>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="compact">
    <div class="pull-left">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit </p>
    </div>
    <div class="pull-right">
    <p>All rights reserved  © Ahotel </p>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar">
<div class="navbar-inner">
<a class="navbar-brand" href="/"><%=image_tag("logo.jpg",class: "img-rounded", alt: "logo")%></a>

<ul class="nav pull-right">
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Help", help_path %></li>
  <li><%= link_to "About", about_path %></li>
  <% case %>
  <% when manager_signed_in?%>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Account <b class="caret"></b></a>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "Create new hotel", new_hotel_path %></li>
        <li><%= link_to "Settings", '#' %></li>
        <li class="divider"></li>
        <li><%= link_to "Logout", destroy_manager_session_path, :method => :delete %></li>
      </ul>
    </li>
    <li> <%= link_to "Logout", destroy_manager_session_path, :method => :delete %></li>

  <% when user_signed_in?%>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Account <b class="caret"></b></a>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "Create new hotel", new_hotel_path %></li>
        <li>
          <% if user_signed_in?%>
          <%= link_to current_user.email, edit_user_registration_path %>
          <% end %>
        </li>
        <li><%= link_to "Settings", '#' %></li>
        <li class="divider"></li>
        <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
      </ul>
    </li>
    <li> <%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>

  <% else %>
    <li><%= link_to "Sign in", new_user_session_path %></li>
  <% end %>

</ul>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ahotel</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
  <div class="row">
      <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
      <% end %>
  </div>

  <div class="row">
    <div class="span10">
    <%= yield %>
    </div>
    <%= render 'layouts/advertisement' %>
  </div>
</div>

<%= render 'layouts/footer' %>


</body>
</html>